Created basic functionality for User page
reekArd/pick-a-pic pull request #2
Opened 2021-04-13 18:32 UTC by reekArd

2021-04-13 18:46 UTC, yoloOnTheBattlefield requested changes

2021-04-13 18:46 UTC, yoloOnTheBattlefield commented on src/components/UserHeader/index.js
> +
destructure

2021-04-13 18:46 UTC, yoloOnTheBattlefield commented on src/components/UserHeader/index.js
> +      </div>
this is quite repetitive, can it be done better?

2021-04-13 18:46 UTC, yoloOnTheBattlefield commented on src/components/UserStats/index.js
> +      <h2 onClick={props.click}>Stats</h2>
handleClick please

2021-04-13 18:46 UTC, yoloOnTheBattlefield commented on src/pages/User/index.js
> +      console.log(data);
no console

2021-04-13 21:01 UTC, redliz5808 commented on src/components/UserHeader/index.js
> +        <span>{userInfo && userInfo.following_count} Following</span>
Could you do one check for userInfo here to make it more concise?

2021-04-14 07:50 UTC, vladciuca commented on src/pages/Search/index.js
> +        `https://api.unsplash.com/search/photos?page=${pageToLoad}&query=${inputValue}&client_id=${process.env.REACT_APP_API_KEY}`
${process.env.REACT_APP_API_KEY} maybe you could move this in its own variable then pass it in the url

2021-04-14 07:51 UTC, vladciuca commented on src/pages/User/index.js
> +        `https://api.unsplash.com/users/${this.state.inputValue}?client_id=${process.env.REACT_APP_API_KEY}`
same here for ${process.env.REACT_APP_API_KEY}

2021-04-14 07:52 UTC, vladciuca commented on src/pages/User/index.js
> +        `https://api.unsplash.com/users/${this.state.inputValue}/collections?page=1&per_page=10&client_id=${process.env.REACT_APP_API_KEY}`
here too

2021-04-14 07:52 UTC, vladciuca commented on src/pages/User/index.js
> +        `https://api.unsplash.com/users/${this.state.inputValue}/statistics?client_id=${process.env.REACT_APP_API_KEY}`
here too

2021-04-14 07:53 UTC, vladciuca approved these changes

2021-04-14 15:24 UTC, merged