Home page styling
reekArd/pick-a-pic pull request #6
Opened 2021-04-15 20:12 UTC by reekArd

Styled the Home page and added a new component PhotoCard

2021-04-15 20:19 UTC, redliz5808 approved these changes
Looks nice! No comments. :)

2021-04-15 20:41 UTC, yoloOnTheBattlefield requested changes

2021-04-15 20:41 UTC, yoloOnTheBattlefield commented on src/components/Feed/index.js
>            console.log(item);
no console

2021-04-15 21:30 UTC, merged

2021-04-16 08:09 UTC, vladciuca reviewed
Clean