Styled the user profile page and components
reekArd/pick-a-pic pull request #7
Opened 2021-04-16 17:31 UTC by reekArd

Worked on the styling of the User page and related components.
Added some more images to the assets/images folder.

2021-04-16 18:47 UTC, yoloOnTheBattlefield requested changes

2021-04-16 18:47 UTC, yoloOnTheBattlefield commented on src/components/Collection/index.js
> +        </Labels>
.map

2021-04-16 18:47 UTC, yoloOnTheBattlefield commented on src/pages/User/index.js
>    };
you don't have a loading flag or something? did you forget about the setup?
Watch the video again: https://floreacristian.teachable.com/courses/from-beginner-to-professional-developer1/lectures/31280909?preview=logged_in

2021-04-16 19:28 UTC, reekArd commented on src/components/Collection/index.js
> +        </Labels>
why map? I just want the 3 first items from the array not all of them...

2021-04-16 19:29 UTC, reekArd commented on src/pages/User/index.js
>    };
Yeah I should definitely add that, thanks!

2021-04-16 20:04 UTC, merged

2021-04-17 00:24 UTC, vladciuca commented on src/components/PhotoCard/index.js
> +          <img src={heartIcon} alt='heart' style={{ marginRight: 5 }} />
styleszzz in  JSX